# SPDX-FileCopyrightText: Â© 2025 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: Apache-2.0

[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/"
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.ci]
fuzz = { runs = 10_000 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
hardhat = "http://127.0.0.1:8545/"
phala = "https://rpc.phala.network"
sepolia = "${SEPOLIA_RPC_URL}"
base = "https://mainnet.base.org"

[etherscan]
phala = { key = "empty", url = "https://explorer-phala-mainnet-0.t.conduit.xyz/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
